#pragma once
#include <windows.h>
#include<iostream>
using namespace std;
HANDLE  hConsole;
int k = 14;
//hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
//SetConsoleTextAttribute(hConsole, k);

/*
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "      @@@@@@@@@@@@                                           @@@@@@@@@@@@     ";
cout << " @@      *@@@@@@@@@@@,                                      @@@@@@@@@@@&      @@   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
cout << "    ,@@@@@@@@@@@@                                               @@@@@@@@@@@@&   ";
*/
void startShowOff()
{
	Sleep(5000);
	cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
	cout << "MMMW0occcccccccccccdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNklcccccccccccclkNMMM" << endl;
	Sleep(10);
	cout << "MMMMNx,             .dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;             .lKWMMM" << endl;
	cout << "KWMMMMNx,             ,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.            .oKWMMMMX" << endl;
	Sleep(10);
	cout << ".c0WMMMMNx,             ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl.            .lKWMMMMXd'" << endl;
	cout << "  .c0WMMMMNx,            .:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.            .lKWMMMMXd'  " << endl;
	Sleep(10);
	cout << "    .c0WMMMMNx,            .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'            .lKWMMMMXd'    " << endl;
	cout << "      .c0WMMMMNx,            .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;            .lKWMMMMXd'      " << endl;
	Sleep(10);
	cout << "        .c0WMMMMNx,            'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.           .lKWMMMMXd'        " << endl;
	cout << "          .c0WMMMMNx,            ,kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc.           .lKWMMMMXd'          " << endl;
	Sleep(10);
	cout << "            .c0WMMMMNx,           .:OWMMMMMMMMMMMMMMMMMMMMMMMMMXo.           .lKWMMMMXd'            " << endl;
	cout << ":.            .c0WMMMMNx,           .c0WMMMMMMMMMMMMMMMMMMMMMXd'           .lKWMMMMXd'             '" << endl;
	Sleep(10);
	cout << "W0c.            .c0WMMMMNx,           .oKMMMMMMMMMMMMMMMMMMNk,           .lKWMMMMXd'            .;xN" << endl;
	cout << "MMWKo.            .c0WMMMMNx,           'dXMMMMMMMMMMMMMMWO;           .lKWMMMMXd'            .:ONMM" << endl;
	Sleep(10);
	cout << "MMMMMXd'            .c0WMMMMNx,           ,kNMMMMMMMMMMW0c.          .lKWMMMMXd'            .c0WMMMM" << endl;
	cout << "MMMMMMMNx;            .c0WMMMMNx,           :0MMMMMMMMKl.          .lKWMMMMXd'            .oKWMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMNk:.           .c0WMMMMNx,         :0MMMMMMXd.          .lKWMMMMXd'            'dXMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMW0c.           .c0WMMMMNx,     ,kNMMMMNKx,          .lKWMMMMXd'            ;xNMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMWKo.           .c0WMMMMNx,.'xNMMMMWk;.          .lKWMMMMXd'           .:kNMMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMMMMMMXd'           .c0WMMMMN0XMMMMW0:.          .lKWMMMMXd'           .c0WMMMMMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMMMMMMXx,           .c0WMMMMMMMWKl.          .lKWMMMMXd'           .lKWMMMMMMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMMMMMMMMMMNk:.          ,0MMMMMMXo.          .lKWMMMMXd'           'dXMMMMMMMMMMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMMMMMMMMMMWOc.       ;kWMMMMNx'          .lKWMMMMXd'           ,xXMMMMMMMMMMMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMMMMMMMMMMMMMMW0l.   ,xNMMMMNk,          .lKWMMMMXd'          .:kNMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMWKd:dXMMMMWO:.        .lkKWMMMMXd'          .cOWMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMW0c.        .l0WMMMMMXd'          .l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo.        .l0WMMMMMXd'          'dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd.        .l0WMMMMWXd'          ,xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMMMOc;;;:kWMMMMMMNx,        .l0WMMMMXdc'         .;kNMMMMWWMMMMMMMKl;;;:dNMMMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMMMMWo     lWMMMMWO;        .l0WMMMMXd'          .cOWMMMMW0c;dXMMMMMO.    ;XMMMMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMMWo     lWMMW0c.       .l0WMMMMXd'          .l0WMMMMNO:.   ,xNMMMO.    ;XMMMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMMMMWo     :KWKl.       .l0WMMMMXd'          'oKWMMMMMWd.       ;kWWd.    ;XMMMMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMMWx.     ':.       .l0WMMMMXd'          ,xXMMMMMMMMMXd'       .;;.     :XMMMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMMMMMNx,            .l0WMMMMXd'        ..;kNMMMMWKk0WMMMMXd'            .lKWMMMMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMMMMMXx,        .c0WMMMMXd'        .cOXWMMMMW0c. .l0WMMMMXd'        .lKWMMMMMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMMMMMMMMMXx,      .dXMMMXx'        .l0WMMMMMW0:.     .l0WMMWO,      .lKWMMMMMMMMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMMMMMMMMMXx,      'd0d'        'oKWMMMMMMMWO;.       .lOO:.     .lKWMMMMMMMMMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMMMMMWOx0WMMMMXx,      .        ,dXMMMMMMMMMMMMNO:.       .      .l0WMMMMXxkXMMMMMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMWO:. .c0WMMMMXx,          .;kNMMMMMMMMMMMMMMMMW0l.          .l0WMMMMXd'  ,xXMMMMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMWO:.     .c0WMMMMXx,       .dNMMMMMMMMMMMMMMMMMMMMW0,       .l0WMMMMXd'      ,xXMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMO,         .c0WMMMMXx,      'ldddddkNMMMMMMW0dddddo:.     .l0WMMMMXd'         .dWMMMMMMMMM" << endl;
	cout << "MMMMMMMMMMW0c.         .c0WMMMMXx'           .OMMMMMMN:           .l0WMMMMXd'          ,xNMMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMW0ONMMMMW0c.         .lKWMMMMXx'         .OMMMMMMN:         .l0WMMMMNd'          ,xNMMMMW0OXMMMM" << endl;
	cout << "MMWO:. ,xNMMMMW0c.        ,OWMMMMMMXxlcccccccdXMMMMMMWklccccccco0WMMMMMMKc.        ,xNMMMMW0c. ,xXMM" << endl;
	Sleep(10);
	cout << "WO:.     ,xNMMMMW0c.    'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:.    ,xNMMMMW0c.     ,xX" << endl;
	cout << "l.         ,xNMMMMW0c.,dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:.,xNMMMMW0c.         ;" << endl;
	Sleep(10);
	cout << "O:.          ,xNMMMMWXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNMMMMW0c.          'd" << endl;
	cout << "MWO:.          ,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.          'dXM" << endl;
	Sleep(10);
	cout << "MMMNO:.         ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.         'dXMMM" << endl;
	cout << "MMMMMNO:.     'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:.     'dXMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMNO:. 'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:. 'dXMMMMMMM" << endl;
	cout << "MMMMMMMMMNOkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOkXMMMMMMMMM" << endl;
	Sleep(10);
	cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
}